### ISSUE TITLE
[1.19.2] Dedicated Server Startup Crash

### ISSUE THREAD

**Issue by MarioAndWeegee3** [sisby-folk/portable-crafting-standalone#1]
[Log from server](https://gist.github.com/MarioAndWeegee3/afc5aa5a4be3202260a32d55734d36ba)

If the mod isn't loaded on the server, none of the functionality works on the client.

**Comment by sleepingdragoninn** [comment]
Reproduced, we'll sort this one out

**Comment by sleepingdragoninn** [comment]
Should be resolved in v1.3.1
