### ISSUE TITLE
most screens don't work on 1.20.4

### ISSUE THREAD

**Issue by Entropy159** [sisby-folk/portable-crafting-standalone#10]
This mod is great and works fine, if you're using a crafting table. None of the other blocks work. I'm on 1.20.4 fabric 0.15.7.

**Comment by sleepingdragoninn** [comment]
reproduced on 1.20.4 with only fapi

**Comment by sleepingdragoninn** [comment]
looks like this is a marking issue - the latest version crashes for anything on 1.20.4, so we've unmarked all versions.
