### ISSUE TITLE
Stonecutter crashes game over a stack

### ISSUE THREAD

**Issue by benben5000** [sisby-folk/portable-crafting-standalone#12]
When using the portable stonecutter and choosing a block which produces more than a full stack, the game usually crashes. If its barely over a stack it usually just hangs for a while and then comes back. but lets say im cutting a stack of a block that produces 4 of another block, resulting in 4 stacks. the game just times out, with the log not telling my anything about what went wrong. just that i timed out and the world i stopping

**Comment by sleepingdragoninn** [comment]
can't reproduce - version?

![java_sWSCdcT4kD](https://github.com/user-attachments/assets/cf0af2c5-6393-4af0-ab5b-0baaf36e7905)

**Comment by benben5000** [comment]
It happens to version 1.2.2 on Mc version 1.20.1. mostly used with modded blocks

**Comment by sleepingdragoninn** [comment]
Can you provide an example of a mod with a recipe that's caused a crash?

**Comment by benben5000** [comment]
It happens with zinc in the create mod f.ex.

https://github.com/user-attachments/assets/c67e1ccd-4c9c-4fde-b028-d4dfeb2c6786

**Comment by benben5000** [comment]
It happens to zinc in the create mod


https://github.com/user-attachments/assets/99e89084-e7a7-47f6-aac0-1f107d82169f

**Comment by sleepingdragoninn** [comment]
not my mod

**Comment by sleepingdragoninn** [comment]
https://modrinth.com/mod/pocket-tools
