### ISSUE TITLE
Incompatibility with Easy Anvils

### ISSUE THREAD

**Issue by Mortycio** [sisby-folk/portable-crafting-standalone#14]
If I use it together with the [Cull Less Leaves](https://modrinth.com/mod/cull-less-leaves) and [More Culling](https://modrinth.com/mod/moreculling) mods, the following error occurs: 
https://mclo.gs/5Vl5BYN

If I remove one of the two aforementioned mods, the game simply crashes and suggests removing the [Portable Crafting](https://modrinth.com/mod/portable-crafting) mod: 
https://mclo.gs/0j1KhKH 

mod version: 3.0.1
minecraft version: 1.20.1
fabric loader: 0.16.0
java version: 17.0.12

**Comment by sleepingdragoninn** [comment]
incompat with easy anvils for reasons outlined in the description, just turn off anvil in the config or uninstall easy anvils

**Comment by Mortycio** [comment]
> incompat with easy anvils for reasons outlined in the description, just turn off anvil in the config or uninstall easy anvils

![image](https://github.com/user-attachments/assets/da78eaa6-55c9-40ca-a575-adcabd4d7438)

Do I have to erase the line 9 about anvil?

**Comment by sleepingdragoninn** [comment]
yeah just remove that line, or add a # before the first "

**Comment by Mortycio** [comment]
Fixed! Thx 😸
