### ISSUE TITLE
Crash with 3.0.2

### ISSUE THREAD

**Issue by Mortycio** [sisby-folk/portable-crafting-standalone#16]
The game crashes when using the latest version of the mod.

Here is the log using version 3.0.1; everything works perfectly.
https://mclo.gs/KD1zAOM

And here is the log using version 3.0.2, which causes the crash.
https://mclo.gs/lU5ixrJ

portable crafting version: 3.0.2 + 1.20
minecraft version: 1.20.1
fabric loader: 0.16.0
java version: 17.0.12

**Comment by sleepingdragoninn** [comment]
thanks for the quick report, I'll check it out - might have compiled the mod with a too-high version of java

**Comment by sleepingdragoninn** [comment]
should be fixed in 3.0.3, cheers!
