### ISSUE TITLE
 [1.19.2] Dedicated Server Crash On Use

### ISSUE THREAD

**Issue by listerla** [sisby-folk/portable-crafting-standalone#2]
Had a crafting table in inventory, pressed V, instant crash. Mod is on server too.
Using Tinkerer's Quilt+ 1.19

[crash-2022-11-23_17.20.26-server.txt](https://github.com/sisby-folk/portable-crafting-standalone/files/10077358/crash-2022-11-23_17.20.26-server.txt)

[crash-2022-11-23_17.21.28-server.txt](https://github.com/sisby-folk/portable-crafting-standalone/files/10077415/crash-2022-11-23_17.21.28-server.txt)

**Comment by sleepingdragoninn** [comment]
Pretty sure this bug was fixed in 1.3.1 - can you confirm your version?

The modrinth version of TQuilt 1.19 beta would've had this issue up until last night, when we pushed out a new version.

**Comment by sleepingdragoninn** [comment]
🐉 Ah wait crash logs have mod tables now - alright I see it's 1.3.1, I'll get digging today.

**Comment by sleepingdragoninn** [comment]
Fixed in 1.3.2 - I'll push through a tquilt version.
