### ISSUE TITLE
[bug] with inventory tabs

### ISSUE THREAD

**Issue by DanMeadWasTaken** [sisby-folk/portable-crafting-standalone#3]
i'm getting this error in quilt 1.19.2

nothing seems to be wrong, other than P.C.S. seems to be calling for a different version of inventory tabs than what is present and/or available on 1.19.2. 

![image](https://user-images.githubusercontent.com/75497984/215465987-66864e5f-8572-453e-ac17-0a23055038ae.png)

**Comment by sleepingdragoninn** [comment]
"0.9.beta" is not valid semantic versioning, which causes this comparison
to fail where it should succeed.

Install an older version, or use this fixed jar from our modpack
https://github.com/sisby-folk/mc-packs/blob/quilt_1.19.2/mods/inventorytabs-0.9.0-beta-1.19.x.jar

**Comment by DanMeadWasTaken** [comment]
Thank ya for this! the version in the link worked- as in prism launcher, the only version i have available to me are 0.9 and 0.8 betas- granted i didn't think to try to look for a version lower than that.
