### ISSUE TITLE
Can't use crafting stations with Ver. 2.2

### ISSUE THREAD

**Issue by Sephoix** [sisby-folk/portable-crafting-standalone#9]
Minecraft version: 1.20.1
Fabric loader: 0.15.6
Mod version: 2.2

I am able to open the crafting stations using right click from hotbar and inventory but using the crafting table and stations does not work. For the crafting table you can place items in the slots but doesn't register any recipes.  
![image](https://github.com/sisby-folk/portable-crafting/assets/85546419/7343998a-43b4-473a-9259-24945417af66)

and other crafting stations look like they did their intended action but after a bit of time the inventory/items revert back to before the crafting.
![image](https://github.com/sisby-folk/portable-crafting/assets/85546419/98bc9a4a-9f5f-4d83-99fa-c360ef5ecb97)
![image](https://github.com/sisby-folk/portable-crafting/assets/85546419/65d82677-26bb-4e5c-81c9-ab414c0abdfb)
![image](https://github.com/sisby-folk/portable-crafting/assets/85546419/6f94a5a5-3b13-4e78-9767-7d8beea2c802)

Here is also the log from my testing with just this mod alone:
https://mclo.gs/1d7SE7H

**Comment by sleepingdragoninn** [comment]
replicated, we'll have a look.

**Comment by sleepingdragoninn** [comment]
1.18 works fine, this affects 1.19 and above - must be why we missed it.

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/portable-crafting/assets/55819817/4d130757-3424-461d-939e-2d1425c3b1f6)

fixed in 2.2.1
